name: 打包应用并上传服务器

on:
  push:
    # push 代码的时候 哪个分支会受到影响 这里是 master 主分支
    branches:
      - master

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库 action/checkout获取代码
        uses: actions/checkout@v1
      # 安装Node18

      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 20.5.0

      - name: 安装npm
        run: npm install -g npm

      # 安装依赖
      - name: 安装依赖
        run: npm install --force

      # 打包
      - name: 打包
        run: npm run build

      # 上传到腾讯云
      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@main
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # SCP参数
          ARGS: '-avzr --delete'
          # 源目录
          SOURCE: 'build'
          # 服务器ip
          REMOTE_HOST: 'http://49.235.118.67/'
          # 用户
          REMOTE_USER: 'root'
          # 目标地址
          TARGET: '/xjdata/nginx/html'
          # 测试ssh连接
          SCRIPT_BEFORE: ls
